'use server';

import { revalidatePath } from 'next/cache';
import { requireUser } from '@/lib/auth/session';
import { generateAlerts, markNotificationRead, markAllRead } from '@/lib/services/notification';
import { fail, type ActionResult } from '@/server/actions/action-utils';

/**
 * Alerts are generated by scanning current state rather than being fired from
 * inside postings, so they stay correct after a reversal. Refreshing is an
 * explicit action rather than a background job — this deployment has no worker,
 * and a stale alert is worse than one the user asked for.
 */
export async function refreshAlertsAction(): Promise<ActionResult<{ created: number }>> {
  try {
    const user = await requireUser();
    const created = await generateAlerts(user.activeCompany.id);
    revalidatePath('/notifications');
    revalidatePath('/dashboard');
    return { ok: true, data: { created } };
  } catch (error) {
    return fail(error);
  }
}

export async function markNotificationReadAction(id: string): Promise<ActionResult<undefined>> {
  try {
    const user = await requireUser();
    await markNotificationRead(user.activeCompany.id, id);
    revalidatePath('/notifications');
    revalidatePath('/dashboard');
    return { ok: true, data: undefined };
  } catch (error) {
    return fail(error);
  }
}

export async function markAllNotificationsReadAction(): Promise<ActionResult<undefined>> {
  try {
    const user = await requireUser();
    await markAllRead(user.activeCompany.id);
    revalidatePath('/notifications');
    revalidatePath('/dashboard');
    return { ok: true, data: undefined };
  } catch (error) {
    return fail(error);
  }
}
