import { prisma } from '@/lib/db';
import { formatMoney } from '@/lib/format';
import { getEtaAlertDays } from '@/lib/services/settings';
import type { NotificationSeverity } from '@prisma/client';
import type { Tx } from '@/lib/db';

/**
 * NotificationService.
 *
 * Alerts are generated by scanning current state rather than being fired from
 * inside postings, so they stay correct after a reversal. Each alert carries a
 * `dedupeKey` that includes the threshold it fired for, which is what stops the
 * same shipment producing a fresh notification on every page load — the 7-day
 * warning is written once, then the 3-day warning once, and so on.
 */

type Candidate = {
  type: string;
  severity: NotificationSeverity;
  relatedEntityType: string;
  relatedEntityId: string;
  title: string;
  message: string;
  dedupeKey: string;
  dueAt: Date | null;
};

export async function generateAlerts(companyId: string): Promise<number> {
  const alertDays = await getEtaAlertDays(prisma as unknown as Tx, companyId);
  const candidates: Candidate[] = [];

  // --- ETA payment alerts: cargo is arriving and the customer still owes ----
  const etaRows = await prisma.$queryRaw<
    Array<{
      shipmentId: string;
      shipmentNumber: string;
      etaDate: Date;
      daysToEta: number;
      customerName: string;
      outstandingUsd: string;
    }>
  >`
    SELECT s."id" AS "shipmentId", s."shipmentNumber", s."etaDate",
           (s."etaDate" - CURRENT_DATE) AS "daysToEta",
           c."customerName",
           SUM(si."totalAmountUsd" - COALESCE((
             SELECT SUM(ra."amountUsd") FROM receipt_allocations ra
             JOIN receipts r ON r."id" = ra."receiptId"
             WHERE ra."salesInvoiceId" = si."id" AND r."status" = 'POSTED'
           ), 0))::text AS "outstandingUsd"
    FROM shipments s
    JOIN sales_invoices si ON si."shipmentId" = s."id" AND si."status" = 'POSTED'
    JOIN customers c ON c."id" = si."customerId"
    WHERE s."companyId" = ${companyId}
      AND s."etaDate" IS NOT NULL
      AND s."etaDate" >= CURRENT_DATE - 1
      AND s."status" <> 'ARRIVED'
    GROUP BY s."id", s."shipmentNumber", s."etaDate", c."id", c."customerName"
    HAVING SUM(si."totalAmountUsd" - COALESCE((
             SELECT SUM(ra."amountUsd") FROM receipt_allocations ra
             JOIN receipts r ON r."id" = ra."receiptId"
             WHERE ra."salesInvoiceId" = si."id" AND r."status" = 'POSTED'
           ), 0)) > 0
  `;

  for (const row of etaRows) {
    // Fire on the tightest threshold the shipment has crossed.
    const threshold = [...alertDays].sort((a, b) => a - b).find((d) => row.daysToEta <= d);
    if (threshold === undefined) continue;

    const when =
      row.daysToEta <= 0
        ? 'arrives today'
        : row.daysToEta === 1
          ? 'arrives tomorrow'
          : `arrives in ${row.daysToEta} days`;

    candidates.push({
      type: 'ETA_PAYMENT_DUE',
      severity: threshold <= 0 ? 'CRITICAL' : threshold <= 3 ? 'WARNING' : 'INFO',
      relatedEntityType: 'Shipment',
      relatedEntityId: row.shipmentId,
      title: `${row.shipmentNumber} ${when}`,
      message: `${row.customerName} still owes ${formatMoney(row.outstandingUsd, 'USD')} against ${row.shipmentNumber}.`,
      dedupeKey: `${companyId}:ETA_PAYMENT_DUE:${row.shipmentId}:${threshold}`,
      dueAt: row.etaDate,
    });
  }

  // --- Loaded but not booked ----------------------------------------------
  const bookingRows = await prisma.shipment.findMany({
    where: {
      companyId,
      status: { in: ['CONTRACT_CREATED', 'AWAITING_LOADING'] },
      OR: [{ bookingNumber: null }, { bookingNumber: '' }],
      purchaseContract: { status: 'POSTED' },
    },
    select: { id: true, shipmentNumber: true, loadingDate: true },
  });

  for (const row of bookingRows) {
    candidates.push({
      type: 'BOOKING_PENDING',
      severity: 'WARNING',
      relatedEntityType: 'Shipment',
      relatedEntityId: row.id,
      title: `${row.shipmentNumber} is awaiting a booking`,
      message: `${row.shipmentNumber} has no booking number or shipping line yet.`,
      dedupeKey: `${companyId}:BOOKING_PENDING:${row.id}`,
      dueAt: null,
    });
  }

  // --- Arrived with documents still outstanding ----------------------------
  const docRows = await prisma.shipment.findMany({
    where: {
      companyId,
      status: { in: ['ARRIVED', 'CUSTOMS_CLEARING', 'CLEARED'] },
      documentStatus: { notIn: ['COMPLETED', 'WITH_CUSTOMER'] },
      purchaseContract: { status: 'POSTED' },
    },
    select: { id: true, shipmentNumber: true, documentStatus: true },
  });

  for (const row of docRows) {
    candidates.push({
      type: 'DOCUMENTS_PENDING',
      severity: 'WARNING',
      relatedEntityType: 'Shipment',
      relatedEntityId: row.id,
      title: `Documents outstanding for ${row.shipmentNumber}`,
      message: `${row.shipmentNumber} has arrived but its documents are still "${row.documentStatus.replaceAll('_', ' ').toLowerCase()}".`,
      dedupeKey: `${companyId}:DOCUMENTS_PENDING:${row.id}:${row.documentStatus}`,
      dueAt: null,
    });
  }

  // --- Overdue customer invoices -------------------------------------------
  const overdueRows = await prisma.$queryRaw<
    Array<{ invoiceId: string; invoiceNumber: string; customerName: string; currency: string; outstanding: string; dueDate: Date; daysOverdue: number }>
  >`
    SELECT si."id" AS "invoiceId", si."invoiceNumber", c."customerName", si."currency", si."dueDate",
           (CURRENT_DATE - si."dueDate") AS "daysOverdue",
           (si."totalAmount" - COALESCE((
              SELECT SUM(ra."amount") FROM receipt_allocations ra
              JOIN receipts r ON r."id" = ra."receiptId"
              WHERE ra."salesInvoiceId" = si."id" AND r."status" = 'POSTED'
           ), 0))::text AS outstanding
    FROM sales_invoices si
    JOIN customers c ON c."id" = si."customerId"
    WHERE si."companyId" = ${companyId}
      AND si."status" = 'POSTED'
      AND si."dueDate" IS NOT NULL
      AND si."dueDate" < CURRENT_DATE
      AND (si."totalAmount" - COALESCE((
              SELECT SUM(ra."amount") FROM receipt_allocations ra
              JOIN receipts r ON r."id" = ra."receiptId"
              WHERE ra."salesInvoiceId" = si."id" AND r."status" = 'POSTED'
           ), 0)) > 0
  `;

  for (const row of overdueRows) {
    // One notification per 30-day band, so a long-overdue invoice does not
    // regenerate an alert every single day.
    const band = Math.floor(row.daysOverdue / 30);
    candidates.push({
      type: 'INVOICE_OVERDUE',
      severity: row.daysOverdue > 60 ? 'CRITICAL' : 'WARNING',
      relatedEntityType: 'SalesInvoice',
      relatedEntityId: row.invoiceId,
      title: `${row.invoiceNumber} is ${row.daysOverdue} days overdue`,
      message: `${row.customerName} owes ${formatMoney(row.outstanding, row.currency)} on ${row.invoiceNumber}.`,
      dedupeKey: `${companyId}:INVOICE_OVERDUE:${row.invoiceId}:${band}`,
      dueAt: row.dueDate,
    });
  }

  if (candidates.length === 0) return 0;

  const result = await prisma.notification.createMany({
    data: candidates.map((c) => ({ companyId, ...c })),
    skipDuplicates: true,
  });

  return result.count;
}

export async function listNotifications(companyId: string, options?: { unreadOnly?: boolean; limit?: number }) {
  return prisma.notification.findMany({
    where: { companyId, ...(options?.unreadOnly ? { readAt: null } : {}) },
    orderBy: [{ readAt: 'asc' }, { createdAt: 'desc' }],
    take: options?.limit ?? 50,
  });
}

export async function countUnread(companyId: string): Promise<number> {
  return prisma.notification.count({ where: { companyId, readAt: null } });
}

export async function markNotificationRead(companyId: string, id: string): Promise<void> {
  await prisma.notification.updateMany({ where: { id, companyId }, data: { readAt: new Date() } });
}

export async function markAllRead(companyId: string): Promise<void> {
  await prisma.notification.updateMany({ where: { companyId, readAt: null }, data: { readAt: new Date() } });
}
